apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum.config: {{ include (print .Template.BasePath "/realm-import-cm.yaml") . | sha256sum }}
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - start-dev
            - '--import-realm'
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-import
      volumes:
        - name: keycloak-import
          configMap:
            name: {{ include "keycloak.fullname" . }}-keycloak-realm-import
            optional: true
