strimzi-kafka-operator:
  replicas: 1
  watchAnyNamespace: true
  labelsExclusionPattern: '(^app.kubernetes.io/(?!part-of)|argocd.argoproj.io/instance).*'
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 768Mi
