global:
  projectDomain: "local.lgc"

replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: default-cluster-issuer
  hosts:
    - host: keycloak.{{ .Values.global.projectDomain }}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: keycloak-tls
      hosts:
        - keycloak.{{ .Values.global.projectDomain }}
